name = "PdfArchiver"
uuid = "51c188b0-c116-11e9-3b36-3d158a5ad1ed"
authors = ["Robert Rudolph"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
